apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      restartPolicy: Always
      containers:
      - image: grafana-img
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: my-grafana
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: password
        - name: DB_NAME
          value: "telegraf"
        - name: DB_URL
          value: "http://influxdb-svc:8086"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana-svc
  labels:
    app: grafana-app
spec:
  selector:
    app: grafana-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grafana