apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-vol-clm
  labels:
    app: mariadb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
spec:
  selector:
    matchLabels:
      app: mariadb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb-app
    spec:
      restartPolicy: Always
      containers:
      - name: mariadb
        image: mariadb-img:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: DB_USER
            valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: user
          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: password
        livenessProbe:
            exec:
              command:
                - sh
                - livenessprobe.sh
            initialDelaySeconds: 30
            periodSeconds: 3
        volumeMounts:
        - name: mariadb-vol
          mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-vol
          persistentVolumeClaim:
            claimName: mariadb-vol-clm
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  labels:
    app: mariadb-app
spec:
  selector:
    app: mariadb-app
  type: ClusterIP
  ports:
    - port: 3306
      name: mysql